// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// delone.cpp
integers xy_tri_cpp(doubles x, doubles y);
extern "C" SEXP _delone_xy_tri_cpp(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(xy_tri_cpp(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_delone_xy_tri_cpp", (DL_FUNC) &_delone_xy_tri_cpp, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_delone(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
